MusicApp/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]


end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord

    validates :email, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: {minimum: 6, allow_nil: true}

    attr_reader :password

    before_validation :ensure_session_token

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            user 
        else
            nil 
        end
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        password_object = BCrypt::Password.new(self.password_digest)
        password_object.is_password?(password)
    end

    def reset_session_token!
        self.session_token = generate_unique_session_token
        self.save! 
        self.session_token
    end

    private

    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end
    
    def generate_unique_session_token
        loop do
            session_token = SecureRandom::urlsafe_base64(16)
            return session_token unless User.exists?(session_token: session_token)
        end
    end

end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token

    
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logged_in?
        !!current_user
    end

    def logout!
         if logged_in? 
            current_user.reset_session_token!
            session[:session] = nil 
            @current_user = nil 
         end
    end

    def require_logged_in
        if !logged_in?
            redirect_to new_session_url 
        end
    end

    def require_logged_out
        if logged_in?
            redirect_to bands_url
        end
    end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :require_logged_in, only: [:destroy]
    before_action :require_logged_out, only: [:new, :create]

    def new
        @user = User.new
        render :new
    end


    def create
        email = params[:user][:email]
        password = params[:user][:password]
        user = User.find_by_credentials(email, password)
        if user
            login!(user)
            redirect_to user_url(user)
        else
            user = User.new(email: params[:user][:email], password: [:user][:password])
            flash.now[:errors] = ["Invalid credentials, Please try again"]
            render :new
        end
    end


    def destroy
        if logged_in?
            logout!
            flash[:messages] = ["Successfully logged out"]
        end

        redirect_to new_session_url        

    end



end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_logged_in, only: [:show]
    before_action :require_logged_out, only: [:new, :create]


    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
  <% if logged_in? %>
    <h2>Welcome, <%= current_user.email %>% %></h2>
  <form action="<%= session_url %>" method="POST">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Logout">
    <% else %>
      <a href="<%= new_user_url %>"> Sign Up </a>
      <br>
      <a href="<%= new_session_url %>"> Log In </a>

  </form>
<% end%>



    <%= yield %>

    <% if flash[:errors] %>
      <% flash[:errors].each do |error|%>
        <p><%= error %><p>
      <% end %>
    <% end %>
  <% if flash[:messages] %>
      <% flash[:messages].each do |message|%>
        <p><%= message %><p>
      <% end %>
    <% end %>
  </body>
</html>

MusicApp/app/views/users/_form.html.erb
<%#  if type == :new %>
    <%#  action_url = users_url %>
    <%#  button_text = 'Sign Up User' %>
<%#  end  %>

<!--
<form action="<%=users_url%>" method="POST">

<label> Email:
    <input type="text" name="user[email]" value="<%= user.email %>">
</label>

<label> Password:
    <input type="password" name="user[password]" value="">
</label>



<input type="submit" value="Sign Up User">

</form> -->

MusicApp/app/views/users/new.html.erb
<h1> Sign Up</h1>

<%#= render 'form', user: @user, type :new %>

<form action="<%=users_url%>" method="POST">

<label> Email:
    <input type="text" name="user[email]" value="<%= @user.email %>">
</label>

<label> Password:
    <input type="password" name="user[password]" value="">
</label>



<input type="submit" value="Sign Up User">

</form>

MusicApp/app/views/users/show.html.erb
<h1> <%= @user.email %> </h1>